### PR TITLE
adds Gemfile and new CSS blocks for CUDA, C, C++

### PR DESCRIPTION
**Pull request by SinaMostafanejad**
This Pull Request adds the following features to the lesson templates:

- Adds a Gemfile to include new plugins such as _jekyll-spaceship_ etc. (Update: The gem file has been deleted from this PR for now.)
- Adds three CSS code blocks and highlighting structures for C, C++ and CUDA C/C++

### CODE REVIEW

**Comment by janash** [comment]
Hi @SinaMostafanejad - adding jekyll spaceship makes the build a bit more complicated. We ran into this with the software fellow posters, as you may remember can see on this issue (https://github.com/MolSSI-Education/2020-software-fellow-posters/issues/24)

If we include spaceship in the template, building may have to be done using GH Actions. Have you looked into this/has this been considered?

**Comment by SinaMostafanejad** [comment]
> Hi @SinaMostafanejad - adding jekyll spaceship makes the build a bit more complicated. We ran into this with the software fellow posters, as you may remember can see on this issue ([MolSSI-Education/2020-software-fellow-posters#24](https://github.com/MolSSI-Education/2020-software-fellow-posters/issues/24))
> 
> If we include spaceship in the template, building may have to be done using GH Actions. Have you looked into this/has this been considered?

Hi @janash, 

I have not looked into this problem. 

Since it causes so much trouble for the build process, I believe we can remove the Gemfile for now and if we realize that people want to use its features in education tutorials, we can bring that back and think about spending more time on it.

In particular, if we want to work on another template for educational contents in near future, it might not be reasonable to spend time on dealing with the requirements of a third-party package that only I am going to use. So, I vote for removing the spaceship plugin altogether for now.

**Comment by janash** [comment]
Okay, this sounds reasonable. I am in favor of switching the template to Jupyter books but it seems like that may not be beneficial for your tutorials. I think we can switch to a central repo for the template, but I haven't gotten to trying this out yet. Should the `gem` file be removed from this pull request for now?

**Comment by SinaMostafanejad** [comment]
> Okay, this sounds reasonable. I am in favor of switching the template to Jupyter books but it seems like that may not be beneficial for your tutorials. I think we can switch to a central repo for the template, but I haven't gotten to trying this out yet. Should the `gem` file be removed from this pull request for now?

Sorry for the late response, the email went to the spam folder for some reason. Yes. I will delete the gem file from the commit.

**Review by janash — APPROVED** [review]

**Pull request merged**
